import os


# Define item dimensions, weights, and base shipping rate per kg in USD
ITEM_SPECS = {
    "hoodie": {"weight": 600, "length": 30, "width": 25, "height": 5},
}

# Estimated distances in kilometers from Accra to each country (sample provided)
DISTANCE_TO_COUNTRY = {
    "Afghanistan": 8240,
    "Albania": 4810,
    "Algeria": 3050,
    "Andorra": 4340,
    "Angola": 2470,
    "Antigua and Barbuda": 7200,
    "Argentina": 9100,
    "Armenia": 5630,
    "Australia": 15300,
    "Austria": 5230,
    "Azerbaijan": 6070,
    "Bahamas": 8470,
    "Bahrain": 5820,
    "Bangladesh": 9580,
    "Barbados": 6960,
    "Belarus": 5830,
    "Belgium": 4940,
    "Belize": 9580,
    "Benin": 320,
    "Bhutan": 9550,
    "Bolivia": 8100,
    "Bosnia and Herzegovina": 5150,
    "Botswana": 4640,
    "Brazil": 6800,
    "Brunei": 12920,
    "Bulgaria": 4780,
    "Burkina Faso": 770,
    "Burundi": 3650,
    "Cabo Verde": 1620,
    "Cambodia": 11300,
    "Cameroon": 1570,
    "Canada": 8600,
    "Central African Republic": 1700,
    "Chad": 1830,
    "Chile": 10000,
    "China": 11600,
    "Colombia": 8530,
    "Comoros": 3910,
    "Congo, Democratic Republic of the": 1820,
    "Congo, Republic of the": 1290,
    "Costa Rica": 9590,
    "Croatia": 5000,
    "Cuba": 8620,
    "Cyprus": 4980,
    "Czech Republic": 5490,
    "Denmark": 5640,
    "Djibouti": 4470,
    "Dominica": 7110,
    "Dominican Republic": 7540,
    "Ecuador": 8820,
    "Egypt": 3900,
    "El Salvador": 9730,
    "Equatorial Guinea": 1260,
    "Eritrea": 4340,
    "Estonia": 6430,
    "Eswatini": 4710,
    "Ethiopia": 3800,
    "Fiji": 18420,
    "Finland": 6700,
    "France": 5000,
    "Gabon": 1180,
    "Gambia": 1550,
    "Georgia": 5520,
    "Germany": 5400,
    "Ghana": 0,  # Accra to Ghana is 0 km
    "Greece": 4900,
    "Grenada": 7230,
    "Guatemala": 9520,
    "Guinea": 1100,
    "Guinea-Bissau": 1360,
    "Guyana": 7270,
    "Haiti": 7630,
    "Honduras": 9620,
    "Hungary": 5300,
    "Iceland": 5990,
    "India": 9200,
    "Indonesia": 11500,
    "Iran": 6130,
    "Iraq": 5000,
    "Ireland": 5600,
    "Israel": 4700,
    "Italy": 5300,
    "Jamaica": 8440,
    "Japan": 12800,
    "Jordan": 4580,
    "Kazakhstan": 7030,
    "Kenya": 4300,
    "Kiribati": 18450,
    "Korea, North": 12500,
    "Korea, South": 12500,
    "Kosovo": 4990,
    "Kuwait": 5450,
    "Kyrgyzstan": 7620,
    "Laos": 10900,
    "Latvia": 6170,
    "Lebanon": 4600,
    "Lesotho": 4890,
    "Liberia": 1120,
    "Libya": 3430,
    "Liechtenstein": 5160,
    "Lithuania": 6110,
    "Luxembourg": 4990,
    "Madagascar": 3720,
    "Malawi": 3900,
    "Malaysia": 11000,
    "Maldives": 8370,
    "Mali": 960,
    "Malta": 4540,
    "Marshall Islands": 18930,
    "Mauritania": 1520,
    "Mauritius": 4510,
    "Mexico": 10500,
    "Micronesia": 17100,
    "Moldova": 5770,
    "Monaco": 5150,
    "Mongolia": 11200,
    "Montenegro": 4910,
    "Morocco": 2760,
    "Mozambique": 4460,
    "Myanmar": 9830,
    "Namibia": 4380,
    "Nauru": 19000,
    "Nepal": 8760,
    "Netherlands": 5200,
    "New Zealand": 16300,
    "Nicaragua": 9760,
    "Niger": 830,
    "Nigeria": 400,
    "North Macedonia": 4870,
    "Norway": 6500,
    "Oman": 6120,
    "Pakistan": 8600,
    "Palau": 15300,
    "Palestine State": 4590,
    "Panama": 9240,
    "Papua New Guinea": 14550,
    "Paraguay": 7900,
    "Peru": 8470,
    "Philippines": 12400,
    "Poland": 5700,
    "Portugal": 4700,
    "Qatar": 5660,
    "Romania": 5290,
    "Russia": 10700,
    "Rwanda": 3560,
    "Saint Kitts and Nevis": 7120,
    "Saint Lucia": 7130,
    "Saint Vincent and the Grenadines": 7130,
    "Samoa": 18800,
    "San Marino": 5290,
    "Sao Tome and Principe": 960,
    "Saudi Arabia": 6100,
    "Senegal": 1620,
    "Serbia": 5100,
    "Seychelles": 4470,
    "Sierra Leone": 1390,
    "Singapore": 11200,
    "Slovakia": 5510,
    "Slovenia": 5130,
    "Solomon Islands": 16400,
    "Somalia": 4150,
    "South Africa": 4700,
    "South Sudan": 2950,
    "Spain": 4600,
    "Sri Lanka": 8310,
    "Sudan": 2750,
    "Suriname": 7410,
    "Sweden": 6200,
    "Switzerland": 5200,
    "Syria": 4550,
    "Tajikistan": 7750,
    "Tanzania": 4050,
    "Thailand": 10700,
    "Timor-Leste": 14100,
    "Togo": 160,
    "Tonga": 18550,
    "Trinidad and Tobago": 7510,
    "Tunisia": 3860,
    "Turkey": 5100,
    "Turkmenistan": 6910,
    "Tuvalu": 18300,
    "Uganda": 3510,
    "Ukraine": 5600,
    "United Arab Emirates": 6800,
    "United Kingdom": 5200,
    "United States": 8500,
    "Uruguay": 8440,
    "Uzbekistan": 7130,
    "Vanuatu": 17080,
    "Vatican City": 5300,
    "Venezuela": 7420,
    "Vietnam": 10400,
    "Yemen": 5360,
    "Zambia": 4110,
    "Zimbabwe": 4010
}

# Define a base rate per km per kg in USD and regional shipping rate adjustments
BASE_RATE_PER_KM_PER_KG = 0.0005  # Example rate
REGIONAL_RATES = {
    "Africa": 0.0004,
    "Europe": 0.0006,
    "Asia": 0.0007,
    "North America": 0.0008,
    "South America": 0.0008,
    "Oceania": 0.0009
}

COUNTRY_TO_REGION = {
    "Afghanistan": "Asia",
    "Albania": "Europe",
    "Algeria": "Africa",
    "Andorra": "Europe",
    "Angola": "Africa",
    "Antigua and Barbuda": "North America",
    "Argentina": "South America",
    "Armenia": "Asia",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Azerbaijan": "Asia",
    "Bahamas": "North America",
    "Bahrain": "Asia",
    "Bangladesh": "Asia",
    "Barbados": "North America",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Belize": "North America",
    "Benin": "Africa",
    "Bhutan": "Asia",
    "Bolivia": "South America",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "South America",
    "Brunei": "Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cabo Verde": "Africa",
    "Cambodia": "Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Chile": "South America",
    "China": "Asia",
    "Colombia": "South America",
    "Comoros": "Africa",
    "Congo, Democratic Republic of the": "Africa",
    "Congo, Republic of the": "Africa",
    "Costa Rica": "North America",
    "Croatia": "Europe",
    "Cuba": "North America",
    "Cyprus": "Asia",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "Djibouti": "Africa",
    "Dominica": "North America",
    "Dominican Republic": "North America",
    "Ecuador": "South America",
    "Egypt": "Africa",
    "El Salvador": "North America",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Europe",
    "Eswatini": "Africa",
    "Ethiopia": "Africa",
    "Fiji": "Oceania",
    "Finland": "Europe",
    "France": "Europe",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Asia",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Greece": "Europe",
    "Grenada": "North America",
    "Guatemala": "North America",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Guyana": "South America",
    "Haiti": "North America",
    "Honduras": "North America",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Ireland": "Europe",
    "Israel": "Asia",
    "Italy": "Europe",
    "Jamaica": "North America",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Kenya": "Africa",
    "Kiribati": "Oceania",
    "Korea, North": "Asia",
    "Korea, South": "Asia",
    "Kosovo": "Europe",
    "Kuwait": "Asia",
    "Kyrgyzstan": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Asia",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Libya": "Africa",
    "Liechtenstein": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Marshall Islands": "Oceania",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mexico": "North America",
    "Micronesia": "Oceania",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Myanmar": "Asia",
    "Namibia": "Africa",
    "Nauru": "Oceania",
    "Nepal": "Asia",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nicaragua": "North America",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Palau": "Oceania",
    "Palestine State": "Asia",
    "Panama": "North America",
    "Papua New Guinea": "Oceania",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "Asia",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Qatar": "Asia",
    "Romania": "Europe",
    "Russia": "Europe",
    "Rwanda": "Africa",
    "Saint Kitts and Nevis": "North America",
    "Saint Lucia": "North America",
    "Saint Vincent and the Grenadines": "North America",
    "Samoa": "Oceania",
    "San Marino": "Europe",
    "Sao Tome and Principe": "Africa",
    "Saudi Arabia": "Asia",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Solomon Islands": "Oceania",
    "Somalia": "Africa",
    "South Africa": "Africa",
    "South Sudan": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Sudan": "Africa",
    "Suriname": "South America",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Syria": "Asia",
    "Tajikistan": "Asia",
    "Tanzania": "Africa",
    "Thailand": "Asia",
    "Timor-Leste": "Asia",
    "Togo": "Africa",
    "Tonga": "Oceania",
    "Trinidad and Tobago": "North America",
    "Tunisia": "Africa",
    "Turkey": "Asia",
    "Turkmenistan": "Asia",
    "Tuvalu": "Oceania",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Asia",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Uruguay": "South America",
    "Uzbekistan": "Asia",
    "Vanuatu": "Oceania",
    "Vatican City": "Europe",
    "Venezuela": "South America",
    "Vietnam": "Asia",
    "Yemen": "Asia",
    "Zambia": "Africa",
    "Zimbabwe": "Africa"
}

def calculate_package_weight(items):
    """Calculate the total weight of the package in kg."""
    total_weight = sum(ITEM_SPECS[item]["weight"] * quantity for item, quantity in items.items() if item in ITEM_SPECS)
    return total_weight / 1000  # Convert to kg

def calculate_dimensional_weight(length, width, height, divisor=5000):
    """Calculate dimensional weight using industry standard divisor."""
    return (length * width * height) / divisor

def calculate_shipping_cost(destination_country, items, margin_percentage=10):
    """Calculate the shipping cost to a specific country based on distance, item weight, and dimensional weight."""
    if destination_country not in DISTANCE_TO_COUNTRY:
        return "N/A"

    # Get the distance and regional base rate
    distance_km = DISTANCE_TO_COUNTRY[destination_country]
    region = COUNTRY_TO_REGION.get(destination_country, "Global")
    base_rate = REGIONAL_RATES.get(region, BASE_RATE_PER_KM_PER_KG)

    # Calculate package weight and dimensional weight
    package_weight = calculate_package_weight(items)
    dimensional_weight = sum(
        calculate_dimensional_weight(ITEM_SPECS[item]["length"], ITEM_SPECS[item]["width"], ITEM_SPECS[item]["height"]) * quantity
        for item, quantity in items.items() if item in ITEM_SPECS
    )
    billable_weight = max(package_weight, dimensional_weight)  # Choose the greater of actual or dimensional weight

    # Calculate the raw shipping cost
    raw_shipping_cost = distance_km * billable_weight * base_rate

    # Apply margin
    total_cost_usd = raw_shipping_cost * (1 + margin_percentage / 100)
    return total_cost_usd

def generate_shipping_cost(items, destination_country):
    """Generate shipping cost estimate for a specific country."""
    cost = calculate_shipping_cost(destination_country, items)
    return cost*10

# Example usage
# items = {
#     "hoodie": 2,  # 2 hoodies
#     "tee": 3,     # 3 t-shirts
#     "shorts": 1,  # 1 pair of shorts
#     "joggers": 2  # 2 joggers
# }

# destination_country = "Algeria"
# print(f"Estimated Shipping Cost to {destination_country}: {generate_shipping_cost(items, destination_country)}")
