# Generated by Django 5.0.6 on 2025-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_payment_product_accessrequest_user_cart_cartobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_ordering',
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
