# Generated by Django 5.0.6 on 2025-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_options_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartobject',
            name='sizeData',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
