# Generated by Django 5.0.6 on 2025-01-27 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_accessrequest_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
