# Generated by Django 5.1.5 on 2025-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_accessrequest_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPriceByRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_method', models.CharField(max_length=100, unique=True)),
                ('ashanti', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('greater_accra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('western', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('eastern', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('northern', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('upper_east', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('upper_west', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bono', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bono_east', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ahafo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savannah', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('western_north', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('oti', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('central', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
