# Generated by Django 5.1.5 on 2025-01-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='ogStock',
        ),
        migrations.AddField(
            model_name='product',
            name='reflectorStock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
