# Generated by Django 5.1.5 on 2025-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_product_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflectorBlack', models.PositiveIntegerField(default=0)),
                ('reflectorGrey', models.PositiveIntegerField(default=0)),
                ('relectorWhite', models.PositiveIntegerField(default=0)),
                ('reflectorPeach', models.PositiveIntegerField(default=0)),
                ('reflectorTPS', models.PositiveIntegerField(default=0)),
                ('ogBlack', models.PositiveIntegerField(default=0)),
                ('ogGrey', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ogStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reflectorStock',
        ),
    ]
