# Generated by Django 5.1.5 on 2025-02-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactData',
        ),
    ]
